name: staff_view_ui
description: "Staff View for Human Resource"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  json_annotation: ^4.9.0
  get_storage: ^2.1.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.0.15
  flutter_pdfview: ^1.3.4
  mobile_scanner: ^6.0.2
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  file_picker: ^5.2.5
  intl: ^0.19.0
  skeletonizer: ^1.4.2
  webview_flutter: ^4.10.0
  reactive_forms: ^17.0.1
  flutter_slidable: ^3.1.2
  flutter_sticky_header: ^0.7.0
  timelines: ^0.1.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  open_file: ^3.2.1
  pinput: ^5.0.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/setting.json
    - assets/langs/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer.ttf
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy.ttf
