// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Staff _$StaffFromJson(Map<String, dynamic> json) => Staff(
      name: json['name'] as String?,
      latinName: json['latinName'] as String?,
      code: json['code'] as String?,
      supervisorId: (json['supervisorId'] as num?)?.toInt(),
      sexId: (json['sexId'] as num?)?.toInt(),
      positionId: (json['positionId'] as num?)?.toInt(),
      departmentId: (json['departmentId'] as num?)?.toInt(),
      officeId: (json['officeId'] as num?)?.toInt(),
      branchId: (json['branchId'] as num?)?.toInt(),
      dateOfBirth: json['dateOfBirth'] == null
          ? null
          : DateTime.parse(json['dateOfBirth'] as String),
      joinDate: json['joinDate'] == null
          ? null
          : DateTime.parse(json['joinDate'] as String),
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      address: json['address'] as String?,
      contractTypeId: (json['contractTypeId'] as num?)?.toInt(),
      staffLevelId: (json['staffLevelId'] as num?)?.toInt(),
      photo: json['photo'] as String?,
      idNumber: json['idNumber'] as String?,
      idType: (json['idType'] as num?)?.toInt(),
      tittleId: (json['tittleId'] as num?)?.toInt(),
      scheduleId: (json['scheduleId'] as num?)?.toInt(),
      id: (json['id'] as num?)?.toInt(),
      statusId: (json['statusId'] as num?)?.toInt(),
      sexName: json['sexName'] as String?,
      sexNameKh: json['sexNameKh'] as String?,
      positionName: json['positionName'] as String?,
      departmentName: json['departmentName'] as String?,
      pathName: json['pathName'] as String?,
      officeName: json['officeName'] as String?,
      branchName: json['branchName'] as String?,
      contractTypeName: json['contractTypeName'] as String?,
      detailInfoString: json['detailInfoString'] as String?,
      photoString: json['photoString'] as String?,
      staffLevelCode: json['staffLevelCode'] as String?,
      supervisorName: json['supervisorName'] as String?,
      statusName: json['statusName'] as String?,
      idTypeName: json['idTypeName'] as String?,
      tittleName: json['tittleName'] as String?,
      scheduleName: json['scheduleName'] as String?,
      salaryModeName: json['salaryModeName'] as String?,
      paymentMethodName: json['paymentMethodName'] as String?,
      salary: (json['salary'] as num?)?.toInt(),
      salaryMode: (json['salaryMode'] as num?)?.toInt(),
      paymentMethodId: (json['paymentMethodId'] as num?)?.toInt(),
      payrollAccountNo: json['payrollAccountNo'] as String?,
    );

Map<String, dynamic> _$StaffToJson(Staff instance) => <String, dynamic>{
      'name': instance.name,
      'latinName': instance.latinName,
      'code': instance.code,
      'supervisorId': instance.supervisorId,
      'sexId': instance.sexId,
      'positionId': instance.positionId,
      'departmentId': instance.departmentId,
      'officeId': instance.officeId,
      'branchId': instance.branchId,
      'dateOfBirth': instance.dateOfBirth?.toIso8601String(),
      'joinDate': instance.joinDate?.toIso8601String(),
      'phone': instance.phone,
      'email': instance.email,
      'address': instance.address,
      'contractTypeId': instance.contractTypeId,
      'staffLevelId': instance.staffLevelId,
      'photo': instance.photo,
      'idNumber': instance.idNumber,
      'idType': instance.idType,
      'tittleId': instance.tittleId,
      'scheduleId': instance.scheduleId,
      'id': instance.id,
      'statusId': instance.statusId,
      'sexName': instance.sexName,
      'sexNameKh': instance.sexNameKh,
      'positionName': instance.positionName,
      'departmentName': instance.departmentName,
      'pathName': instance.pathName,
      'officeName': instance.officeName,
      'branchName': instance.branchName,
      'contractTypeName': instance.contractTypeName,
      'detailInfoString': instance.detailInfoString,
      'photoString': instance.photoString,
      'staffLevelCode': instance.staffLevelCode,
      'supervisorName': instance.supervisorName,
      'statusName': instance.statusName,
      'idTypeName': instance.idTypeName,
      'tittleName': instance.tittleName,
      'scheduleName': instance.scheduleName,
      'salaryModeName': instance.salaryModeName,
      'paymentMethodName': instance.paymentMethodName,
      'salary': instance.salary,
      'salaryMode': instance.salaryMode,
      'paymentMethodId': instance.paymentMethodId,
      'payrollAccountNo': instance.payrollAccountNo,
    };
